#!/usr/bin/env python

"""
    Author: Mingi Jeong

    node harness
    
    purpose: 
    - automated convert nodes
"""

# python modules
import os

# ROS modules
import rospy
import rospkg

# custom modules
from time_sync_bag_to_csv.ConvertHarness import ConvertHarness


def main():
    # node initialization
    rospy.init_node('time_sync_bag_to_csv')
    rospy.sleep(1)

    # ----------------------------------------------------------
    # load files
    # ----------------------------------------------------------

    # launch file
    rospack = rospkg.RosPack()
    launch_file = [rospack.get_path('time_sync_bag_to_csv') + "/launch/converter.launch"]

    # bag files: main directory where bags located
    path = '/root/bagfile/' # docker
    # path = '/home/minkbrook/Desktop/random/'
    bag_files = []

    bag_file = rospy.get_param('~bag_file')
    bag_files.append(path+bag_file)

    # walker file finder 
    # https://mkyong.com/python/python-how-to-list-all-files-in-a-directory/
    # r=root, d=directories, f = files
    # for r, d, f in os.walk(path):
    #     for file in f:
    #         if '.bag' in file:
    #             bag_files.append(os.path.join(r, file))

    print(launch_file)
    
    # ----------------------------------------------------------
    # argument building
    # ----------------------------------------------------------
    roslaunch_args = []
    for bag_file in bag_files:
        roslaunch_args.append(["bag_file:={}".format(bag_file), "bag_file_run:=true"])

    rospy.logwarn("cli arguments {}". format(roslaunch_args))


    # ----------------------------------------------------------
    # auto run
    # ----------------------------------------------------------
    convert_harness = ConvertHarness() # initialization   
    
    for roslaunch_arg in roslaunch_args:
        convert_harness.run_convert(launch_file, roslaunch_arg)



if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        rospy.logerr("executing convert harness node failed")
        pass