#!/usr/bin/env python

"""
    Author: Mingi Jeong

    node csv_converter_multiobs
    
    purpose: 
    - main converter node for multi obstacle
"""

# python modules
import csv
# from ruamel import yaml

# ROS modules
import rospy

# custom modules
from time_sync_bag_to_csv.converter_multiobs import ConverterMultiobs


def main():
    # node initialization
    rospy.init_node('time_sync_bag_to_csv')
    rospy.sleep(2)

    # output_file_name = "test.csv"

    # class instantiation for time sync subscriber
    converter = ConverterMultiobs()
    # converter.initializer()
    
    ### main time sync and csv writer
    converter.time_sync_callback()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        rospy.logerr("executing csv converter node failed")
        pass